apiVersion: v1
kind: ConfigMap

metadata:
  name: order-config
  namespace: ecommerce

data:
  DB_HOST: database-1.c9o8eugeq7eq.ap-southeast-2.rds.amazonaws.com
  DB_NAME: order_db

  USER_SERVICE_URL: http://user-service/users
  PRODUCT_SERVICE_URL: http://product-service:5001/products
