apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  namespace: {{ .Values.userService.namespace }}

spec:
  replicas: {{ .Values.userService.replicaCount }}

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:

      - name: user-service

        image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"

        ports:
        - containerPort: {{ .Values.userService.containerPort }}

        env:

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: user-config
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: DB_PASSWORD
